# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Personal metrics (left)
        uses: lowlighter/metrics@latest
        with:
          filename: metrics-left.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: SpenserJ
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Edmonton
          plugin_introduction: yes
          plugin_introduction_title: no
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_lines: yes
          plugin_languages: yes
          plugin_languages_ignored: php
          plugin_languages_sections: recently-used
      - name: Personal metrics (right)
        uses: lowlighter/metrics@latest
        with:
          filename: metrics-right.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: SpenserJ
          template: classic
          config_order: stars, habits
          config_timezone: America/Edmonton
          base: ""
          plugin_stars: yes
          plugin_stars_limit: 4
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_trim: yes
